### PR TITLE
[Manta] init refactoring

### PR DESCRIPTION
**Pull request by zhenfeizhang**

### CODE REVIEW

**Comment by stechu** [comment]
@zhenfeizhang  is this ready for review?

**Comment by zhenfeizhang** [comment]
yes

**Comment by stechu** [comment]
Thanks for this high quality PR.

1. I could reproduce the CI error:
    ``` 
    cargo check --release --no-default-features
    error[E0412]: cannot find type `Vec` in this scope
    --> src/commitment.rs:48:15
    |
    48 |     type Input = Vec<u8>;
    |                  ^^^ not found in this scope
    ```
    please take a look.

2.  any consideration on choosing pedersen window size 8  * 256?  would be nice to document the design choice somewhere? (doesn't have to do in this PR)
3. kind of related to 2. I noticed that in arkworks R1CS tutorial, they use the `TECompressor`. Additionally, they use different window size of leaf and non-leaf hashes. It might be worth investigating whether this can bring any performance benefit(doesn't have to do in this PR as well).  I just post their code here:
```
// `WINDOW_SIZE * NUM_WINDOWS` = 2 * 256 bits = enough for hashing two outputs.
impl pedersen::Window for TwoToOneWindow {
    const WINDOW_SIZE: usize = 128;
    const NUM_WINDOWS: usize = 4;
}

pub type LeafHash = PedersenCRHCompressor<EdwardsProjective, TECompressor, LeafWindow>;

#[derive(Clone, PartialEq, Eq, Hash)]
pub struct LeafWindow;

// `WINDOW_SIZE * NUM_WINDOWS` = 2 * 256 bits = enough for hashing two outputs.
impl pedersen::Window for LeafWindow {
    const WINDOW_SIZE: usize = 144;
    const NUM_WINDOWS: usize = 4;
}
```
Happy to merge it once the CI is fixed.

**Comment by zhenfeizhang** [comment]
> Thanks for this high quality PR.
> 
>     1. I could reproduce the CI error:
>        ```
>        cargo check --release --no-default-features
>        error[E0412]: cannot find type `Vec` in this scope
>        --> src/commitment.rs:48:15
>        |
>        48 |     type Input = Vec<u8>;
>        |                  ^^^ not found in this scope
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        please take a look.
> 
>     2. any consideration on choosing pedersen window size 8  * 256?  would be nice to document the design choice somewhere? (doesn't have to do in this PR)
> 
>     3. kind of related to 2. I noticed that in arkworks R1CS tutorial, they use the `TECompressor`. Additionally, they use different window size of leaf and non-leaf hashes. It might be worth investigating whether this can bring any performance benefit(doesn't have to do in this PR as well).  I just post their code here:
> 
> 
> ```
> // `WINDOW_SIZE * NUM_WINDOWS` = 2 * 256 bits = enough for hashing two outputs.
> impl pedersen::Window for TwoToOneWindow {
>     const WINDOW_SIZE: usize = 128;
>     const NUM_WINDOWS: usize = 4;
> }
> 
> pub type LeafHash = PedersenCRHCompressor<EdwardsProjective, TECompressor, LeafWindow>;
> 
> #[derive(Clone, PartialEq, Eq, Hash)]
> pub struct LeafWindow;
> 
> // `WINDOW_SIZE * NUM_WINDOWS` = 2 * 256 bits = enough for hashing two outputs.
> impl pedersen::Window for LeafWindow {
>     const WINDOW_SIZE: usize = 144;
>     const NUM_WINDOWS: usize = 4;
> }
> ```
> 
> Happy to merge it once the CI is fixed.

This was Tom's work. 
It is not integrated into the released version yet.
We will need to wait till 0.3.0 for this feature.

**Comment by zhenfeizhang** [comment]
And CI is fixed.

**Pull request merged**
